const { test, expect } = require('@playwright/test');
const { ToolsPage } = require('./tools-page');
const {
	shouldSkipWithoutMail,
	NO_MAIL_CAPTURE,
	uniqueBookerEmail,
	waitForMail,
} = require('../../utils/mail');

const EMAIL_NOT_CORRECT = 'Email address is not correct';
const TEST_EMAIL_SENT = 'Check your email address';
const TEST_EMAIL_SUBJECT = 'Seatreg test email';

const MALFORMED_EMAIL = 'not-an-address';

/* The screen a site owner is sent to when nothing the plugin emails is arriving,
   so both tools here are only worth anything if they work on a site where the
   thing they are testing is broken.

   The test mail is the only place in the suite that proves wp_mail() reaches the
   plugin at all; every other mail assertion rides on a booking. */

test.describe('SeatReg Tools screen', () => {
	let tools;

	test.beforeEach(async ({ page }) => {
		tools = new ToolsPage(page);

		await tools.goto();
	});

	test('sends a test mail, and refuses an address it cannot send to', async ({ page }) => {
		test.skip(await shouldSkipWithoutMail(page), NO_MAIL_CAPTURE);

		/* The refusal happens in the browser, so the request never being made is
		   what it amounts to. The mail log cannot answer this: it looks an address
		   up with sanitize_email(), which reduces a malformed one to the empty
		   string it reads as "everything". */
		const asked = [];

		page.on('request', (request) => {
			if ((request.postData() ?? '').includes('action=seatreg_send_test_email')) {
				asked.push(request);
			}
		});

		await tools.sendTestEmail(MALFORMED_EMAIL);

		await expect(tools.errorToast).toHaveText(EMAIL_NOT_CORRECT);
		expect(asked).toHaveLength(0);

		const address = uniqueBookerEmail('tools');

		await tools.sendTestEmail(address);

		/* The screen says nothing but this, so it is also the sign the request
		   finished and the log is worth reading. */
		await expect(tools.successToast).toHaveText(TEST_EMAIL_SENT);

		const sent = await waitForMail(page, address);

		expect(sent.subject).toBe(TEST_EMAIL_SUBJECT);
		expect(asked).toHaveLength(1);
	});

	/* The image is generated by the bundled phpqrcode against the gd extension as
	   the screen renders. Nothing else in the suite exercises that path, and the
	   approved booking receipt can carry the same code. */
	test('shows a QR code it generated', async () => {
		await expect(tools.qrCode).toBeVisible();
		expect(await tools.qrCodeLoaded()).toBe(true);
	});
});
